
import { Account, AccountType, Currency, AppState } from './types';

export const BASE_CURRENCY = Currency.IDR;

export const INITIAL_ACCOUNTS: Account[] = [
  // ASSETS
  { id: 'acc_1', name: 'Cash', type: AccountType.ASSET, emoji: '💵', isSystem: true },
  { id: 'acc_2', name: 'Bank Account', type: AccountType.ASSET, emoji: '🏦' },
  { id: 'acc_3', name: 'Accounts Receivable', type: AccountType.ASSET, emoji: '🗒️' },
  { id: 'acc_19', name: 'Emergency Fund', type: AccountType.ASSET, emoji: '🛡️' },

  // LIABILITIES
  { id: 'acc_4', name: 'Credit Card', type: AccountType.LIABILITY, emoji: '💳' },
  { id: 'acc_5', name: 'Accounts Payable', type: AccountType.LIABILITY, emoji: '📝' },
  { id: 'acc_18', name: 'Personal Loan', type: AccountType.LIABILITY, emoji: '🤝' },

  // EQUITY
  { id: 'acc_6', name: 'Owner Capital', type: AccountType.EQUITY, emoji: '💼' },
  { id: 'acc_7', name: 'Retained Earnings', type: AccountType.EQUITY, emoji: '📈' },

  // INCOME
  { id: 'acc_8', name: 'Sales Revenue', type: AccountType.INCOME, emoji: '💰' },
  { id: 'acc_9', name: 'Service/Side Income', type: AccountType.INCOME, emoji: '🎁' },

  // EXPENSES
  { id: 'acc_10', name: 'Rent Expense', type: AccountType.EXPENSE, emoji: '🏠' },
  { id: 'acc_11', name: 'Utilities (Water/Elec)', type: AccountType.EXPENSE, emoji: '💡' },
  { id: 'acc_12', name: 'Groceries', type: AccountType.EXPENSE, emoji: '🛒' },
  { id: 'acc_13', name: 'Transportation/Gas', type: AccountType.EXPENSE, emoji: '🚗' },
  { id: 'acc_14', name: 'Entertainment/Dining', type: AccountType.EXPENSE, emoji: '🍿' },
  { id: 'acc_15', name: 'Education/Tuition', type: AccountType.EXPENSE, emoji: '🎓' },
  { id: 'acc_16', name: 'Medical/Health', type: AccountType.EXPENSE, emoji: '💊' },
  { id: 'acc_17', name: 'Insurance', type: AccountType.EXPENSE, emoji: '🛡️' },
];

export const INITIAL_STATE: AppState = {
  entries: [],
  accounts: INITIAL_ACCOUNTS,
  budgets: []
};

export const RATES_TO_IDR: Record<Currency, number> = {
  [Currency.IDR]: 1,
  [Currency.USD]: 15600,
  [Currency.EUR]: 16900,
  [Currency.JPY]: 103.5,
};
export const CATEGORY_ICONS = ['💵', '🏦', '🗒️', '🛡️', '💳', '📝', '🤝', '💼', '📈', '💰', '🎁', '🏠', '💡', '🛒', '🚗', '🍿', '🎓', '💊'];


export const TRANSLATIONS = {
  en: {
    'nav.home': 'Dashboard',
    'nav.journal': 'Journal',
    'nav.budget': 'Budget',
    'nav.settings': 'Settings',

    'type.Asset': 'Asset',
    'type.Liability': 'Liability',
    'type.Equity': 'Equity',
    'type.Income': 'Income',
    'type.Expense': 'Expense',

    'acc.Cash': 'Cash',
    'acc.Bank Account': 'Bank Account',
    'acc.Accounts Receivable': 'Accounts Receivable',
    'acc.Emergency Fund': 'Emergency Fund',
    'acc.Credit Card': 'Credit Card',
    'acc.Accounts Payable': 'Accounts Payable',
    'acc.Personal Loan': 'Personal Loan',
    'acc.Owner Capital': 'Owner Capital',
    'acc.Retained Earnings': 'Retained Earnings',
    'acc.Sales Revenue': 'Sales Revenue',
    'acc.Service/Side Income': 'Service/Side Income',
    'acc.Rent Expense': 'Rent Expense',
    'acc.Utilities (Water/Elec)': 'Utilities (Water/Elec)',
    'acc.Groceries': 'Groceries',
    'acc.Transportation/Gas': 'Transportation/Gas',
    'acc.Entertainment/Dining': 'Entertainment/Dining',
    'acc.Education/Tuition': 'Education/Tuition',
    'acc.Medical/Health': 'Medical/Health',
    'acc.Insurance': 'Insurance',

    'mode.expense': 'Expense',
    'mode.income': 'Income',
    'mode.transfer': 'Transfer',
    'mode.debt': 'Debt',

    'ui.amount': 'Amount',
    'ui.category': 'Category',
    'ui.account': 'Account',
    'ui.from': 'Pay from',
    'ui.to': 'Deposit to',
    'ui.transfer_from': 'Source Account',
    'ui.transfer_to': 'Destination Account',
    'ui.debt_from': 'Borrow From',
    'ui.debt_to': 'Receive In',
    'ui.debt_pay': 'Repayment (Pay Back)',
    'ui.debt_borrow': 'Borrowing (New Debt)',
    'ui.debt_repay_to': 'Repay To',
    'ui.debt_repay_from': 'Pay From',

    'entry.new_title': 'New Entry',
    'entry.edit_title': 'Edit Entry',
    'entry.detail_title': 'Transaction Detail',
    'entry.date': 'Date',
    'entry.desc': 'Description',
    'entry.save': 'Save Transaction',
    'entry.delete_confirm': 'Delete this transaction?',
    'entry.delete_success': 'Transaction deleted.',
    'entry.select_account': 'Select Account',
    'entry.select_category': 'Select Category',
    'entry.loading_account': 'Loading account...',
    'entry.loading_category': 'Loading category...',
    'entry.no_account_found': 'Account not found.',
    'entry.no_category_found': 'Category not found.',
    'entry.add_account': 'Add Account',
    'entry.add_category': 'Add Category',

    'dash.header': 'Overview',
    'dash.morning': 'Good Morning',
    'dash.afternoon': 'Good Afternoon',
    'dash.evening': 'Good Evening',
    'dash.net_income': 'Net Income',
    'dash.total_income': 'Income',
    'dash.total_expenses': 'Expenses',
    'dash.total_assets': 'Assets',
    'dash.total_liabilities': 'Liabilities',
    'dash.total_equity': 'Net Worth',
    'dash.net_result': 'Net Result',
    'dash.profit': 'Profit',
    'dash.loss': 'Loss',
    'dash.this_period': 'this period',
    'dash.insight_title': 'Financial Insights',
    'dash.rule_title': 'The 1/3 Rule',
    'dash.rule_pass': 'Great! You are saving more than 33% of your income.',
    'dash.rule_fail': 'Try to keep expenses below 2/3 of your income to meet the 1/3 rule.',
    'dash.savings_rate': 'savings rate',
    "dash.total_balance": "Total Balance",
    "dash.available_funds": "Available funds across all assets",

    'time.today': 'Today',
    'time.week': 'Week',
    'time.month': 'Month',
    'time.year': 'Year',
    'time.all': 'All',

    'set.title': 'Settings',
    'set.preferences': 'Preferences',
    'set.dark_mode': 'Dark Mode',
    'set.notifications': 'Notifications',
    'set.on': 'On',
    'set.off': 'Off',
    'set.enabled': 'Enabled',
    'set.disabled': 'Disabled',
    'set.language': 'Language',
    'set.currency': 'Currency',
    'set.currency_desc': 'All amounts across the app will be converted to this currency.',
    'set.data_mgmt': 'Data Management',

    'budget.title': 'Budgets',
    'budget.no_budgets': 'No budgets set.',
    'budget.add_hint': 'Tap + to set a spending limit.',
    'budget.new_limit': 'New Budget',
    'budget.edit_limit': 'Edit Budget',
    'budget.expense_acc': 'Expense Category',
    'budget.select_category': 'Select a category',
    'budget.monthly_limit': 'Monthly Limit',
    'budget.update': 'Update Budget',
    'budget.save': 'Create Budget',
    'budget.exists_alert': 'A budget for this category already exists.',
    'budget.delete_confirm': 'Delete this budget?',

    'journal.search_placeholder': 'Search transactions...',
    'journal.filter_all': 'All Types',
    'journal.no_entries': 'No entries found.',
    'journal.tap_to_add': 'Tap + to start tracking.',
    'journal.no_results': 'No results match your search.',

    'login.error_empty': 'Please fill in all fields',
    'login.error_invalid_email': 'Invalid email format',
    'login.error_failed': 'Login failed. Please try again.',

    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to your account to continue',
    'login.email': 'Email Address',
    'login.email_placeholder': 'Enter your email',
    'login.password': 'Password',
    'login.password_placeholder': 'Enter your password',
    'login.remember_me': 'Remember Me',
    'login.forgot_password': 'Forgot Password?',
    'login.loading': 'Signing In...',
    'login.button': 'Sign In',
    'login.sign_in': 'Sign In',
    'login.sign_up': 'Sign Up',
    'login.no_account': `Don't have an account?`,

    // Registration Header & Subtitle
    'register.title': 'Create Account',
    'register.subtitle': 'Join us to start managing your finances',

    // Form Labels & Placeholders
    'register.full_name': 'Full Name',
    'register.name_placeholder': 'Enter your full name',
    'register.email': 'Email Address',
    'register.email_placeholder': 'Enter your email',
    'register.password': 'Password',
    'register.password_placeholder': 'Create a password',
    'register.password_hint': 'At least 6 characters',
    'register.confirm_password': 'Confirm Password',
    'register.confirm_password_placeholder': 'Confirm your password',

    // Terms & Conditions
    'register.agree_terms': 'I agree to the Terms of Service and Privacy Policy',

    // Buttons & Links
    'register.button': 'Create Account',
    'register.loading': 'Creating account...',
    'register.already_account': 'Already have an account?',
    'register.sign_in': 'Sign in here',

    // Error Messages
    'register.error_empty': 'Please fill in all fields',
    'register.error_name_short': 'Name must be at least 2 characters',
    'register.error_invalid_email': 'Invalid email format',
    'register.error_password_short': 'Password must be at least 6 characters',
    'register.error_password_mismatch': 'Passwords do not match',
    'register.error_terms': 'Please agree to the terms and conditions',
    'register.error_failed': 'Registration failed. Please try again.',
    'register.email_confirmation_message': 'Please check your email to confirm your account',

    'common.saving': 'Saving...',
  },
  id: {
    'nav.home': 'Beranda',
    'nav.journal': 'Jurnal',
    'nav.budget': 'Anggaran',
    'nav.settings': 'Pengaturan',

    'type.Asset': 'Aset',
    'type.Liability': 'Liabilitas',
    'type.Equity': 'Ekuitas',
    'type.Income': 'Pendapatan',
    'type.Expense': 'Beban',

    'acc.Cash': 'Kas Tunai',
    'acc.Bank Account': 'Rekening Bank',
    'acc.Accounts Receivable': 'Piutang Usaha',
    'acc.Emergency Fund': 'Dana Darurat',
    'acc.Credit Card': 'Kartu Kredit',
    'acc.Accounts Payable': 'Utang Usaha',
    'acc.Personal Loan': 'Pinjaman Pribadi',
    'acc.Owner Capital': 'Modal Pemilik',
    'acc.Retained Earnings': 'Laba Ditahan',
    'acc.Sales Revenue': 'Penjualan',
    'acc.Service/Side Income': 'Sampingan',
    'acc.Rent Expense': 'Sewa',
    'acc.Utilities (Water/Elec)': 'Listrik/Air',
    'acc.Groceries': 'Belanja',
    'acc.Transportation/Gas': 'Transportasi',
    'acc.Entertainment/Dining': 'Makan Luar',
    'acc.Education/Tuition': 'Pendidikan',
    'acc.Medical/Health': 'Kesehatan',
    'acc.Insurance': 'Asuransi',

    'mode.expense': 'Pengeluaran',
    'mode.income': 'Pendapatan',
    'mode.transfer': 'Transfer',
    'mode.debt': 'Utang',

    'ui.amount': 'Jumlah',
    'ui.category': 'Kategori',
    'ui.account': 'Akun',
    'ui.from': 'Bayar dari',
    'ui.to': 'Simpan ke',
    'ui.transfer_from': 'Dari Akun',
    'ui.transfer_to': 'Ke Akun',
    'ui.debt_from': 'Pinjam Dari',
    'ui.debt_to': 'Terima Di',
    'ui.debt_pay': 'Bayar Utang',
    'ui.debt_borrow': 'Pinjam Baru',
    'ui.debt_repay_to': 'Bayar Ke',
    'ui.debt_repay_from': 'Bayar Dari',

    'entry.new_title': 'Entri Baru',
    'entry.edit_title': 'Edit Entri',
    'entry.detail_title': 'Detail Transaksi',
    'entry.date': 'Tanggal',
    'entry.desc': 'Keterangan',
    'entry.save': 'Simpan Transaksi',
    'entry.delete_confirm': 'Hapus transaksi ini?',
    'entry.delete_success': 'Transaksi berhasil dihapus.',
    'entry.select_account': 'Pilih Akun',
    'entry.select_category': 'Pilih Kategori',
    'entry.loading_account': 'Memuat Akun...',
    'entry.loading_category': 'Memuat Kategori...',
    'entry.no_account_found': 'Akun tidak ditemukan.',
    'entry.no_category_found': 'Kategori tidak ditemukan.',
    'entry.add_account': 'Tambah Akun',
    'entry.add_category': 'Tambah Kategori',

    'dash.header': 'Ringkasan',
    'dash.morning': 'Selamat Pagi',
    'dash.afternoon': 'Selamat Siang',
    'dash.evening': 'Selamat Malam',
    'dash.net_income': 'Laba Bersih',
    'dash.total_income': 'Pendapatan',
    'dash.total_expenses': 'Pengeluaran',
    'dash.total_assets': 'Aset',
    'dash.total_liabilities': 'Kewajiban',
    'dash.total_equity': 'Kekayaan Bersih',
    'dash.net_result': 'Hasil Bersih',
    'dash.profit': 'Laba',
    'dash.loss': 'Rugi',
    'dash.this_period': 'periode ini',
    'dash.insight_title': 'Wawasan Keuangan',
    'dash.rule_title': 'Aturan 1/3',
    'dash.rule_pass': 'Bagus! Anda menabung lebih dari 33% pendapatan.',
    'dash.rule_fail': 'Cobalah jaga pengeluaran di bawah 2/3 pendapatan untuk aturan 1/3.',
    'dash.savings_rate': 'rasio tabungan',

    "dash.total_balance": "Total Saldo",
    "dash.available_funds": "Dana tersedia di seluruh aset",

    'time.today': 'Hari Ini',
    'time.week': 'Minggu',
    'time.month': 'Bulan',
    'time.year': 'Tahun',
    'time.all': 'Semua',

    'set.title': 'Pengaturan',
    'set.preferences': 'Preferensi',
    'set.dark_mode': 'Mode Gelap',
    'set.notifications': 'Notifikasi',
    'set.on': 'Aktif',
    'set.off': 'Nonaktif',
    'set.enabled': 'Aktif',
    'set.disabled': 'Nonaktif',
    'set.language': 'Bahasa',
    'set.currency': 'Mata Uang',
    'set.currency_desc': 'Semua jumlah di aplikasi akan dikonversi ke mata uang ini.',
    'set.data_mgmt': 'Manajemen Data',

    'budget.title': 'Anggaran',
    'budget.no_budgets': 'Belum ada anggaran.',
    'budget.add_hint': 'Ketuk + untuk menetapkan batas pengeluaran.',
    'budget.new_limit': 'Anggaran Baru',
    'budget.edit_limit': 'Ubah Anggaran',
    'budget.expense_acc': 'Kategori Pengeluaran',
    'budget.select_category': 'Pilih kategori',
    'budget.monthly_limit': 'Batas Bulanan',
    'budget.update': 'Perbarui Anggaran',
    'budget.save': 'Buat Anggaran',
    'budget.exists_alert': 'Anggaran untuk kategori ini sudah ada.',
    'budget.delete_confirm': 'Hapus anggaran ini?',

    'journal.search_placeholder': 'Cari transaksi...',
    'journal.filter_all': 'Semua Jenis',
    'journal.no_entries': 'Tidak ada entri.',
    'journal.tap_to_add': 'Ketuk + untuk mulai mencatat.',
    'journal.no_results': 'Hasil pencarian tidak ditemukan.',

    'login.error_empty': 'Mohon isi semua kolom',
    'login.error_invalid_email': 'Format email tidak valid',
    'login.error_failed': 'Gagal masuk. Silakan coba lagi.',

    'login.title': 'Selamat Datang Kembali',
    'login.subtitle': 'Masuk ke akun Anda untuk melanjutkan',
    'login.email': 'Alamat Email',
    'login.email_placeholder': 'Masukkan email Anda',
    'login.password': 'Kata Sandi',
    'login.password_placeholder': 'Masukkan kata sandi Anda',
    'login.remember_me': 'Ingat Saya',
    'login.forgot_password': 'Lupa Kata Sandi?',
    'login.loading': 'Sedang Masuk...',
    'login.button': 'Login',
    'login.sign_in': 'Masuk',
    'login.sign_up': 'Daftar',
    'login.no_account': 'Belum punya akun?',

    // Registration Header & Subtitle
    'register.title': 'Buat Akun',
    'register.subtitle': 'Bergabunglah dengan kami untuk mulai mengelola keuangan Anda',

    // Form Labels & Placeholders
    'register.full_name': 'Nama Lengkap',
    'register.name_placeholder': 'Masukkan nama lengkap Anda',
    'register.email': 'Alamat Email',
    'register.email_placeholder': 'Masukkan email Anda',
    'register.password': 'Kata Sandi',
    'register.password_placeholder': 'Buat kata sandi',
    'register.password_hint': 'Minimal 6 karakter',
    'register.confirm_password': 'Konfirmasi Kata Sandi',
    'register.confirm_password_placeholder': 'Konfirmasi kata sandi Anda',

    // Terms & Conditions
    'register.agree_terms': 'Saya menyetujui Ketentuan Layanan dan Kebijakan Privasi',

    // Buttons & Links
    'register.button': 'Buat Akun',
    'register.loading': 'Sedang membuat akun...',
    'register.already_account': 'Sudah punya akun?',
    'register.sign_in': 'Masuk di sini',

    // Error Messages
    'register.error_empty': 'Mohon isi semua kolom',
    'register.error_name_short': 'Nama minimal harus 2 karakter',
    'register.error_invalid_email': 'Format email tidak valid',
    'register.error_password_short': 'Kata sandi minimal harus 6 karakter',
    'register.error_password_mismatch': 'Kata sandi tidak cocok',
    'register.error_terms': 'Mohon setujui syarat dan ketentuan',
    'register.error_failed': 'Pendaftaran gagal. Silakan coba lagi.',
    'register.email_confirmation_message': 'Silakan periksa email Anda untuk mengonfirmasi akun Anda',
    'common.saving': 'Menyimpan...',
  }
};
